backend/src/main/java/com/shallwecode/backend/config/AppConfig.java, backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java
🌟개요
---
security 버그 주석 처리
🌐연결된 Issues
---
#7 
📋작업사항
---
- security 버그 주석 처리
---
✅체크리스트
---
=> fix: security 버그 주석 처리

backend/src/main/java/com/shallwecode/backend/test/application/controller/TestController.java, backend/src/main/java/com/shallwecode/backend/test/application/dto/TestDTO.java, backend/src/main/java/com/shallwecode/backend/test/application/service/TestService.java, backend/src/main/java/com/shallwecode/backend/test/domain/aggregate/Test.java, backend/src/main/java/com/shallwecode/backend/test/domain/repository/TestRepository.java, backend/src/main/java/com/shallwecode/backend/test/domain/service/TestDomainService.java
🌟개요
---
샘플 백엔드 디렉토리 구조
🌐연결된 Issues
---
#10 
📋작업사항
---
- 샘플 구조 설정
---
✅체크리스트
---
=> chore: 샘플 백엔드 디렉토리 구조

backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java, backend/src/main/java/com/shallwecode/backend/user/application/dto/UserSaveDTO.java, backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/User.java, backend/src/main/java/com/shallwecode/backend/user/domain/repository/UserRepository.java, backend/src/main/java/com/shallwecode/backend/user/domain/service/UserDomainService.java
🌟개요
---
🌐연결된 Issues
---
📋작업사항
---
---
✅체크리스트
---
=> feat: #5 회원 기능 위한 기본구조 생성

backend/src/main/java/com/shallwecode/backend/problem/application/controller/ProblemController.java, backend/src/main/java/com/shallwecode/backend/problem/application/dto/ProblemReqDTO.java, backend/src/main/java/com/shallwecode/backend/problem/domain/aggregate/Problem.java, backend/src/main/java/com/shallwecode/backend/problem/domain/aggregate/Testcase.java, backend/src/main/java/com/shallwecode/backend/problem/domain/service/ProblemDomainService.java
🌟개요
--- 문제 CRUD 작업 진행중
📋작업사항
--- ProblemDomainService 코드 작성 및 ProblemController 코드 작성
--- 문제 생성, 수정, 삭제 기능 작성
---
=> feat: #6 문제 추가, 수정, 삭제 기능 작성

frontend/src/App.vue, frontend/src/assets/css/resetcss.css, frontend/src/components/common/Header.vue, frontend/src/router/user.js, frontend/src/views/user/UserList.vue
🌟개요
---
Header.vue 구현
🌐연결된 Issues
---
close #19 
📋작업사항
---
Header.vue 구현
---
✅체크리스트
---
=> feat: Header.vue 구현

backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java, backend/src/main/java/com/shallwecode/backend/user/application/dto/UserUpdateDTO.java, backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java, backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/User.java, backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/UserInfo.java, backend/src/main/java/com/shallwecode/backend/user/domain/repository/UserRepository.java, backend/src/main/java/com/shallwecode/backend/user/domain/service/UserDomainService.java
🌟개요
---
🌐연결된 Issues
---
#5 
📋작업사항
---
---
✅체크리스트
---
=> feat: #5 회원 닉네임 수정 기능 구현

backend/.gitignore, backend/build.gradle, backend/src/main/java/com/shallwecode/backend/config/QueryDslConfig.java, backend/src/main/java/com/shallwecode/backend/problem/application/controller/TryController.java, backend/src/main/java/com/shallwecode/backend/problem/application/dto/FindMyTryResDTO.java, backend/src/main/java/com/shallwecode/backend/problem/application/dto/FindTryResDTO.java, backend/src/main/java/com/shallwecode/backend/problem/application/dto/SaveTryReqDTO.java, backend/src/main/java/com/shallwecode/backend/problem/application/service/TryService.java, backend/src/main/java/com/shallwecode/backend/problem/domain/aggregate/Try.java, backend/src/main/java/com/shallwecode/backend/problem/domain/aggregate/TryLanguage.java, backend/src/main/java/com/shallwecode/backend/problem/domain/repository/TryRepository.java, backend/src/main/java/com/shallwecode/backend/problem/domain/service/TryDomainService.java, frontend/src/assets/css/resetcss.css, frontend/src/components/common/Header.vue, frontend/src/components/user/MyCodingRoomList.vue, frontend/src/components/user/MyFriendManagement.vue, frontend/src/components/user/MyInfo.vue, frontend/src/components/user/MyNotiList.vue, frontend/src/components/user/MyProblemList.vue, frontend/src/router/user.js, frontend/src/views/user/MyPage.vue, frontend/src/views/user/MyPageTap.vue
🌟개요
---
풀이 시도 관련 기능 구현
🌐연결된 Issues
---
📋작업사항
---
풀이 시도 생성
풀이 시도 삭제
내 풀이 시도 조회
마이페이지 풀이 목록 
---
✅체크리스트
---
=> feat: 풀이 시도 관련 기능 구현

backend/src/main/java/com/shallwecode/backend/common/exception/ErrorCode.java, backend/src/main/java/com/shallwecode/backend/user/application/controller/FriendController.java, backend/src/main/java/com/shallwecode/backend/user/application/dto/FindUserDTO.java, backend/src/main/java/com/shallwecode/backend/user/application/dto/FoundUserDTO.java, backend/src/main/java/com/shallwecode/backend/user/application/dto/SaveFriendDTO.java, backend/src/main/java/com/shallwecode/backend/user/application/dto/SaveFriendReqDTO.java, backend/src/main/java/com/shallwecode/backend/user/application/dto/SaveNotiDTO.java, backend/src/main/java/com/shallwecode/backend/user/application/service/FriendService.java, backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/Friend.java, backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/FriendStatus.java, backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/Noti.java, backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/NotiType.java, backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/UserInfo.java, backend/src/main/java/com/shallwecode/backend/user/domain/repository/FriendRepository.java, backend/src/main/java/com/shallwecode/backend/user/domain/repository/NotiRepository.java, backend/src/main/java/com/shallwecode/backend/user/domain/service/FriendDomainService.java, backend/src/main/java/com/shallwecode/backend/user/domain/service/NotiDomainService.java, backend/src/main/java/com/shallwecode/backend/user/domain/service/UserDomainService.java
🌟개요
---
친구 요청 백엔드 기능 구현
🌐연결된 Issues
---
close #27 
📋작업사항
---
- 친구 요청 백엔드 기능 구현
- 친구 요청 시 알림 보내는 기능 구현
- 친구 요청 조건도 포함
- 자기 자신에게 요청 못보냄, 이미 보낸 요청에 대해 거절하기 전까지 재요청 불가
---
✅체크리스트
---
=> feat: 친구 요청 백엔드 기능 구현

backend/src/main/java/com/shallwecode/backend/problem/application/controller/ProblemController.java, backend/src/main/java/com/shallwecode/backend/problem/application/dto/ProblemResDTO.java, backend/src/main/java/com/shallwecode/backend/problem/application/service/ProblemService.java, backend/src/main/java/com/shallwecode/backend/problem/domain/aggregate/Problem.java, backend/src/main/java/com/shallwecode/backend/problem/domain/aggregate/Testcase.java, backend/src/main/java/com/shallwecode/backend/problem/domain/service/ProblemDomainService.java, backend/src/test/java/com/shallwecode/backend/problem/domain/service/ProblemDomainServiceTest.java
🌟개요
---
🌐연결된 Issues
---
close #{이슈넘버}
📋작업사항
--- 
- 관리자 문제 상세 조회 기능 구현 
- 한 문제에 여러개의 테스트 케이스가 있을 수 있으므로 List 로 반환
---
✅체크리스트
---
=> feat: 문제 상세 조회 백엔드 기능

backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java, backend/src/main/java/com/shallwecode/backend/user/application/dto/UserSaveDTO.java, backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java, backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/UserInfo.java, backend/src/main/java/com/shallwecode/backend/user/domain/repository/UserRepository.java, backend/src/main/java/com/shallwecode/backend/user/domain/service/UserDomainService.java
🌟개요
---
🌐연결된 Issues
---
📋작업사항
---
- 회원 가입 기능 구현
---
- 이메일 유효성 검사 기능 추가
✅체크리스트
---
=> feat: #5 회원 가입 기능 구현

backend/src/main/java/com/shallwecode/backend/problem/application/controller/ProblemController.java, backend/src/main/java/com/shallwecode/backend/problem/application/dto/ProblemResListDTO.java, backend/src/main/java/com/shallwecode/backend/problem/application/service/ProblemService.java, backend/src/main/java/com/shallwecode/backend/problem/domain/service/ProblemDomainService.java, backend/src/test/java/com/shallwecode/backend/problem/domain/service/ProblemDomainServiceTest.java
🌟개요
---
🌐연결된 Issues
---
close #{이슈넘버}
📋작업사항
---
- 문제 목록 조회 기능 구현 완료 
- 테스트 코드 작성
---
- Swagger 작성
- 미 사용 코드 제거
✅체크리스트
---
=> feat: 문제 목록 조회 기능 

backend/src/main/java/com/shallwecode/backend/problem/application/controller/ProblemController.java, backend/src/main/java/com/shallwecode/backend/problem/application/controller/TryController.java, backend/src/main/java/com/shallwecode/backend/problem/application/dto/FindMyProblemResDTO.java, backend/src/main/java/com/shallwecode/backend/problem/application/dto/FindMyTryResDTO.java, backend/src/main/java/com/shallwecode/backend/problem/application/service/ProblemService.java, backend/src/main/java/com/shallwecode/backend/problem/application/service/TryService.java, backend/src/main/java/com/shallwecode/backend/problem/domain/service/ProblemDomainService.java, backend/src/main/java/com/shallwecode/backend/problem/domain/service/TryDomainService.java, frontend/package-lock.json, frontend/package.json, frontend/src/components/user/MyProblemList.vue
🌟개요
---
풀이 시도 조회 구현 및 프론트 연결까지 했습니다
🌐연결된 Issues
---
close #23 
📋작업사항
---
---
✅체크리스트
---
=> feat: 풀이 시도 관련 기능

backend/src/main/java/com/shallwecode/backend/common/exception/ErrorCode.java, backend/src/main/java/com/shallwecode/backend/user/application/controller/FriendController.java, backend/src/main/java/com/shallwecode/backend/user/application/dto/FindFriendDTO.java, backend/src/main/java/com/shallwecode/backend/user/application/dto/UpdateFriendReqDTO.java, backend/src/main/java/com/shallwecode/backend/user/application/service/FriendService.java, backend/src/main/java/com/shallwecode/backend/user/domain/repository/FriendRepository.java, backend/src/main/java/com/shallwecode/backend/user/domain/service/FriendDomainService.java
🌟개요
---
친구 요청 수락, 거절 백엔드 기능 구현
🌐연결된 Issues
---
close #39 
📋작업사항
---
- 친구 요청 수락과 거절 기능 구현
- 수락과 거절은 다른 컨트롤러로 구현
- 두 컨트롤러는 같은 service를 구현
---
✅체크리스트
---
=> feat: 친구 요청 수락, 거절 백엔드 기능 구현

backend/src/main/java/com/shallwecode/backend/problem/application/controller/ProblemController.java, backend/src/main/java/com/shallwecode/backend/problem/application/controller/TryController.java, backend/src/main/java/com/shallwecode/backend/problem/application/service/TryService.java, frontend/src/components/user/MyProblemList.vue
🌟개요
---
풀이 시도 상세 조회
🌐연결된 Issues
---
close #23 
📋작업사항
---
풀이 시도 상세 조회
---
✅체크리스트
---
=> feat: 풀이 시도 상세 조회

backend/src/main/java/com/shallwecode/backend/user/application/controller/NotiController.java, backend/src/main/java/com/shallwecode/backend/user/application/dto/NotiResListDTO.java, backend/src/main/java/com/shallwecode/backend/user/application/service/NotiService.java, backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/Noti.java, backend/src/main/java/com/shallwecode/backend/user/domain/service/NotiDomainService.java
🌟개요
---
헤더, 마이페이지 알림 조회 백엔드 기능 구현
🌐연결된 Issues
---
close #41
📋작업사항
---
- 헤더 알림 조회 구현
- 마이페이지 알림 조회 구현
- 헤더는 읽지 않은 알림만 조회
- 마이페이지는 모든 알림 조회
---
✅체크리스트
---
=> feat: 헤더, 마이페이지 알림 조회 백엔드 기능 구현

backend/src/main/java/com/shallwecode/backend/user/application/controller/FriendController.java, backend/src/main/java/com/shallwecode/backend/user/application/dto/FriendResListDTO.java, backend/src/main/java/com/shallwecode/backend/user/application/service/FriendService.java, backend/src/main/java/com/shallwecode/backend/user/domain/service/FriendDomainService.java
🌟개요
---
친구 목록 조회 기능 백엔드 구현
🌐연결된 Issues
---
close #46 
📋작업사항
---
- 친구 목록 조회 기능 백엔드 구현
---
✅체크리스트
---
=> feat: 친구 목록 조회 기능 백엔드 구현

backend/src/main/java/com/shallwecode/backend/user/domain/service/FriendDomainService.java
🌟개요
---
친구 목록 조회 수정
🌐연결된 Issues
---
📋작업사항
---
- 친구 목록 조회 Accepted만 불러오도록 수정
---
✅체크리스트
---
=> fix: 친구 목록 조회 Accepted만 불러오도록 수정

backend/src/main/java/com/shallwecode/backend/user/application/controller/FriendController.java, backend/src/main/java/com/shallwecode/backend/user/application/service/FriendService.java, backend/src/main/java/com/shallwecode/backend/user/domain/service/FriendDomainService.java
🌟개요
---
친구 신청 목록 조회 백엔드 기능 구현
🌐연결된 Issues
---
close #49 
📋작업사항
---
- 친구 신청 목록 조회 백엔드 기능 구현
---
✅체크리스트
---
=> feat: 친구 신청 목록 조회 백엔드 기능 구현

backend/src/main/java/com/shallwecode/backend/common/exception/ErrorCode.java, backend/src/main/java/com/shallwecode/backend/user/application/controller/FriendController.java, backend/src/main/java/com/shallwecode/backend/user/application/service/FriendService.java, backend/src/main/java/com/shallwecode/backend/user/domain/repository/FriendRepository.java, backend/src/main/java/com/shallwecode/backend/user/domain/service/FriendDomainService.java
🌟개요
---
친구 삭제 기능 구현
🌐연결된 Issues
---
close #51 
📋작업사항
---
- 친구 삭제 기능 구현
- 커스텀 예외 처리
---
✅체크리스트
---
=> feat: 친구 삭제 기능 구현

backend/src/main/java/com/shallwecode/backend/common/exception/ErrorCode.java, backend/src/main/java/com/shallwecode/backend/user/application/controller/NotiController.java, backend/src/main/java/com/shallwecode/backend/user/application/dto/UpdateNotiReqDTO.java, backend/src/main/java/com/shallwecode/backend/user/application/service/NotiService.java, backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/Noti.java, backend/src/main/java/com/shallwecode/backend/user/domain/service/NotiDomainService.java
🌟개요
---
알림 읽음 상태 변경 백엔드 기능 구현
🌐연결된 Issues
---
close #55 
📋작업사항
---
- 알림 Id로 요청을 받고 해당 알림의 읽음 상태를 변경
---
✅체크리스트
---
=> feat: 알림 읽음 상태 변경 백엔드 기능 구현

backend/src/main/java/com/shallwecode/backend/user/application/dto/NotiResListDTO.java, backend/src/main/java/com/shallwecode/backend/user/domain/service/NotiDomainService.java, frontend/src/App.vue, frontend/src/components/common/Header.vue, frontend/src/components/user/MyFriendManagement.vue, frontend/src/components/user/MyNotiList.vue, frontend/src/views/user/MyPageTap.vue
🌟개요
---
마이페이지 알림 및 친구 목록
🌐연결된 Issues
---
close #44 
📋작업사항
---
알림 프론트 연결
친구 프론트 연결
---
✅체크리스트
---
=> feat: 마이페이지 알림 및 친구 목록

frontend/src/views/user/Login.vue
🌟개요
---
로그인 프론트 구현
🌐연결된 Issues
---
close #58 
📋작업사항
---
로그인 프론트 구현
---
✅체크리스트
---
=> feat: 로그인 프론트 구현

backend/src/main/java/com/shallwecode/backend/problem/application/controller/CoopController.java
🌟개요
---
엔드포인트 수정
🌐연결된 Issues
---
close #{이슈넘버}
📋작업사항
---
엔드포인트 수정
---
✅체크리스트
---
=> fix: 엔드포인트 수정

frontend/src/components/Problem/ProbListComponent.vue, frontend/src/components/Problem/SearchBar.vue, frontend/src/views/Problem/AdminProbList.vue
🌟개요
---
🌐연결된 Issues
---
close #65
📋작업사항
---
- 문제 목록 검색 기능 구현
---
✅체크리스트
---
=> feat: 문제 목록 검색 기능 구현

frontend/src/components/Problem/PageBar.vue, frontend/src/components/Problem/ProbListComponent.vue, frontend/src/views/Problem/AdminProbList.vue
🌟개요
---
🌐연결된 Issues
---
close #67 
📋작업사항
---
- 페이징 처리 기능 구현
---
✅체크리스트
---
=> feat: 문제 목록 조회 페이징 기능 구현

backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/AuthType.java, backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/SocialType.java, backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/UserInfo.java
🌟개요
---
DB 변경 사항을 엔티티에 반영
🌐연결된 Issues
---
close #70
📋작업사항
---
- UserInfo 엔티티 필드 수정과 타입 변경
---
✅체크리스트
---
=> chore: DB 변경 사항을 엔티티에 반영

backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java, backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java, backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/UserInfo.java, backend/src/main/java/com/shallwecode/backend/user/domain/repository/UserRepository.java
🌟개요
---
🌐연결된 Issues
---
close #73 
📋작업사항
---
---
✅체크리스트
---
=> feat: 회원 조회 추가, swagger 설명 추가

backend/src/main/java/com/shallwecode/backend/problem/application/controller/CodingRoomController.java, backend/src/main/java/com/shallwecode/backend/problem/application/controller/CoopController.java, backend/src/main/java/com/shallwecode/backend/problem/application/service/CodingRoomService.java, backend/src/main/java/com/shallwecode/backend/problem/application/service/CoopService.java, backend/src/main/java/com/shallwecode/backend/problem/domain/service/CodingRoomDomainService.java, backend/src/main/java/com/shallwecode/backend/problem/domain/service/CoopDomainService.java
🌟개요
---
🌐연결된 Issues
---
close #75 
📋작업사항
---
=> feat: 코딩방 예외처리 구현

backend/src/main/java/com/shallwecode/backend/problem/application/controller/ProblemController.java, backend/src/main/java/com/shallwecode/backend/problem/application/service/ProblemService.java, backend/src/main/java/com/shallwecode/backend/problem/domain/service/ProblemDomainService.java, backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/UserInfo.java
🌟개요
--- 미시도 문제, 도전한 문제, 해결한 문제를 반환 메소드 구현
--- UserInfo 엔티티의 @Build 어노테이션에서 에러 발생해서 @AllArgsConstructor 선언 추가함
🌐연결된 Issues
---
close #77
=> feat: 미시도 문제, 도전한 문제, 해결한 문제를 반환 메소드 구현

backend/src/main/java/com/shallwecode/backend/problem/application/controller/CompileController.java, backend/src/main/java/com/shallwecode/backend/problem/application/dto/CompileReqDTO.java, backend/src/main/java/com/shallwecode/backend/problem/application/dto/CompileResDTO.java, backend/src/main/java/com/shallwecode/backend/problem/application/service/CompileService.java, backend/src/main/java/com/shallwecode/backend/problem/application/service/CustomClassLoader.java, backend/src/main/java/com/shallwecode/backend/problem/application/service/JavaSourceFromString.java
🌟개요
---
자바 컴파일 기능
🌐연결된 Issues
---
close #81
📋작업사항
---
자바 컴파일 기능
---
✅체크리스트
---
=> feat: 자바 컴파일 기능

backend/src/main/java/com/shallwecode/backend/common/exception/ErrorCode.java, backend/src/main/java/com/shallwecode/backend/config/ChatHandler.java, backend/src/main/java/com/shallwecode/backend/config/WebSocketConfig.java, backend/src/main/java/com/shallwecode/backend/problem/application/dto/SendChatDTO.java
🌟개요
---
🌐연결된 Issues
---
closes #84
📋작업사항
---
- 웹소켓 연결 오류 수정
- 연결시 독립된 세션이 아닌 하나의 세션리스트로 공유되던 버그 수정
- 5명의 인원 넘어서 연결 시도 시 연결되던 버그 수정
---
✅체크리스트
---
=> fix: WebSocket 오류 수정

frontend/src/components/user/MyInfo.vue, frontend/src/views/Home.vue, frontend/src/views/user/UserList.vue
🌟개요
---
🌐연결된 Issues
#93 
📋작업사항
---  미시도, 시도, 푼 문제 API 프론트와 연동
=> feat: 미시도, 시도, 푼 문제 API 프론트와 연동 #93

frontend/package-lock.json, frontend/package.json, frontend/src/components/codingroom/CodeEditor.vue, frontend/src/main.js, websocket-server/.gitignore, websocket-server/index.js, websocket-server/package-lock.json, websocket-server/package.json
🌟개요
---
동시 편집 기능 구현했습니다.
다만, node.js로 구현된 서버를 따로 구동해야 해당 기능이 작동합니다.
🌐연결된 Issues
---
Closes #86 
📋작업사항
---
동시 편집 구현
---
✅체크리스트
---
=> feat: 동시 편집 구현

backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java, backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/UserInfo.java, frontend/src/components/admin/UserListComponent.vue, frontend/src/views/user/UserList.vue
🌟개요
🌐연결된 Issues
---
Closes #93 
📋작업사항
--- 유저 엔티티의 양방향 매핑으로 인해서 유저 목록 조회시
--- 무한 참조 문제가 발생해서 단방향 매핑으로 변경했습니다.
--- 유저 - 친구 & 유저 - 알림 사이의 관계들을 모두 양방향에서 단방향 매핑으로 변경
--- 프론트에서 이제 유저 목록 조회 가능
=> feat: 유저 엔티티 수정 및 유저 목록 조회 프론트 구현

websocket-server/package-lock.json, websocket-server/package.json
🌟개요
---
패키지 버전 수정
🌐연결된 Issues
---
Closes #{이슈넘버}
📋작업사항
---
패키지 버전 수정
---
✅체크리스트
---
=> fix: 패키지 버전 수정

websocket-server/package-lock.json, websocket-server/package.json
🌟개요
---
패키지 수정
🌐연결된 Issues
---
Closes #{이슈넘버}
📋작업사항
---
패키지 수정
---
✅체크리스트
---
=> fix: 패키지 수정

backend/src/main/java/com/shallwecode/backend/config/AppConfig.java, backend/src/main/java/com/shallwecode/backend/oauth2/config/SecurityConfig.java, backend/src/main/java/com/shallwecode/backend/oauth2/jwt/filter/JwtAuthenticationProcessingFilter.java, backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java, backend/src/main/java/com/shallwecode/backend/user/application/dto/UserSaveDTO.java, backend/src/main/java/com/shallwecode/backend/user/domain/service/UserDomainService.java, backend/src/main/resources/application-jwt.yml, frontend/src/views/user/SignUp.vue
🌟개요
---
소셜 로그인 오류 수정
🌐연결된 Issues
---
Closes #60 
📋작업사항
---
- 소셜 로그인 오류 수정
---
✅체크리스트
---
=> chore: 소셜 로그인 오류 수정

frontend/src/components/common/Header.vue
🌟개요
---
헤더 수정
🌐연결된 Issues
---
Closes #{이슈넘버}
📋작업사항
---
헤더 수정
---
✅체크리스트
---
=> fix: 헤더 수정

backend/src/main/java/com/shallwecode/backend/oauth2/CustomOAuth2User.java, backend/src/main/java/com/shallwecode/backend/oauth2/OAuthAttributes.java, backend/src/main/java/com/shallwecode/backend/oauth2/config/SecurityConfig.java, backend/src/main/java/com/shallwecode/backend/oauth2/handler/OAuth2LoginSuccessHandler.java, backend/src/main/java/com/shallwecode/backend/oauth2/jwt/filter/JwtAuthenticationProcessingFilter.java, backend/src/main/java/com/shallwecode/backend/oauth2/jwt/service/JwtService.java, backend/src/main/java/com/shallwecode/backend/problem/application/controller/ProblemController.java, backend/src/main/java/com/shallwecode/backend/user/application/controller/FriendController.java, backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java, backend/src/main/java/com/shallwecode/backend/user/application/dto/FindUserDetailDTO.java, backend/src/main/java/com/shallwecode/backend/user/application/dto/UserSaveDTO.java, backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java, backend/src/main/java/com/shallwecode/backend/user/domain/service/UserDomainService.java, backend/src/main/resources/application-jwt.yml, frontend/src/components/common/Header.vue, frontend/src/stores/apiClient.js, frontend/src/stores/auth.js, frontend/src/views/Home.vue, frontend/src/views/user/Login.vue, frontend/src/views/user/SignUp.vue
🌟개요
---
소셜 로그인, 시큐리티 수정 및 회원가입, 회원 상세 조회, 로그아웃 구현
🌐연결된 Issues
---
Closes #111 #112 
📋작업사항
---
- 소셜 로그인, 시큐리티 로직 변경
- 토큰 하나만 이동하도록 수정
- 회원 상세 조회 , 회원 가입, 로그아웃 구현
- 프론트 공통 요청 로직 구현
- 인증 필터 안거치는 로직 구현
---
✅체크리스트
---
=> fix: 소셜 로그인, 시큐리티 수정 및 회원가입, 회원 상세 조회, 로그아웃 구현

backend/src/main/java/com/shallwecode/backend/oauth2/jwt/filter/JwtAuthenticationProcessingFilter.java, backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java, frontend/src/stores/apiClient.js, frontend/src/stores/auth.js
🌟개요
---
로그인 문제 해결, 소셜 인증 엔드포인트 인증 필터 제거
🌐연결된 Issues
---
Closes #114 
📋작업사항
---
- 로그인 문제 해결, 소셜 인증 엔드포인트 인증 필터 제거
---
✅체크리스트
---
=> fix: 로그인 문제 해결, 소셜 인증 엔드포인트 인증 필터 제거

backend/src/main/java/com/shallwecode/backend/common/exception/ErrorCode.java, backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java, backend/src/main/java/com/shallwecode/backend/user/domain/service/UserDomainService.java, backend/src/test/java/com/shallwecode/backend/user/application/service/UserServiceTest.java
🌟개요
---
🌐연결된 Issues
---
Closes #117
📋작업사항
---
- 회원 crud 기본 테스트 코드 추가
- ErrorCode 회원 유효성 검사 추가
---
✅체크리스트
---
=> test: 회원 기본 crud 테스트 코드

backend/src/main/java/com/shallwecode/backend/config/ChatHandler.java, backend/src/main/java/com/shallwecode/backend/oauth2/config/SecurityConfig.java, backend/src/main/java/com/shallwecode/backend/oauth2/jwt/filter/JwtAuthenticationProcessingFilter.java, backend/src/main/java/com/shallwecode/backend/problem/application/controller/CoopController.java, frontend/src/components/codingroom/ChatArea.vue
🌟개요
---
🌐연결된 Issues
---
Closes #110
📋작업사항
---
- 각각 로그인 하여 세션별 채팅 기능 버그 수정
---
- onMount에 코딩방 번호가 10번으로 고정되어있음.
- 각자 로그인한 계정의 방 번호를 넣어서 테스트 해보세요. 
✅체크리스트
---
=> fix: 로그인후 세션별 채팅 기능 버그 수정

backend/src/main/java/com/shallwecode/backend/user/application/controller/FriendController.java, backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java, backend/src/main/java/com/shallwecode/backend/user/application/dto/friend/FindFriendDetailDTO.java, backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java
🌟개요
---
회원 탈퇴 기능과 친구 프로필 조회 백엔드 기능 구현
🌐연결된 Issues
---
Closes #122 
📋작업사항
---
- 회원 탈퇴 기능 추가
- 친구 프로필 조회 기능 추가
---
✅체크리스트
---
=> feat: 회원 탈퇴 기능와 친구 프로필 조회 백엔드 기능 구현

backend/src/main/java/com/shallwecode/backend/user/application/controller/FriendController.java, backend/src/main/java/com/shallwecode/backend/user/application/controller/NotiController.java, backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java, backend/src/main/java/com/shallwecode/backend/user/application/dto/user/UserUpdateDTO.java, backend/src/main/java/com/shallwecode/backend/user/application/service/FriendService.java, backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java, backend/src/main/java/com/shallwecode/backend/user/domain/service/FriendDomainService.java, backend/src/main/java/com/shallwecode/backend/user/domain/service/UserDomainService.java, backend/src/test/java/com/shallwecode/backend/user/application/service/UserServiceTest.java
🌟개요
---
백 프로젝트 토큰에서의 회원 정보 사용하는 코드로 변경 및 간단한 수정
🌐연결된 Issues
---
Closes #126
📋작업사항
---
- 닉네임 변경 오류 수정
- 토큰에서 userId 빼오는 로직 추가
- 주석 제거
---
✅체크리스트
---
=> chore: 백 프로젝트 토큰에서의 회원 정보 사용하는 코드로 변경 및 간단한 수정

backend/src/main/java/com/shallwecode/backend/problem/application/controller/ProblemController.java, frontend/src/components/admin/PageBar.vue, frontend/src/components/admin/ProbListComponent.vue, frontend/src/components/admin/ProbListItemComponent.vue, frontend/src/components/admin/SearchBar.vue, frontend/src/components/admin/UserListComponent.vue, frontend/src/components/user/MyProblemList.vue, frontend/src/views/Home.vue, frontend/src/views/admin/AdminPage.vue, frontend/src/views/user/MyPageTap.vue, frontend/src/views/user/SignUp.vue, frontend/src/views/user/UserList.vue
🌟개요
---
메인, 회원가입, 마이페이지, 관리자페이지 프론트 리팩토링
🌐연결된 Issues
---
Closes #{이슈넘버}
📋작업사항
---
- 메인, 회원 목록에서 친구 없을 경우에 보일 친구 목록 화면 추가
- 회원 가입 화면 css 리팩토링
- 마이페이지 css 리팩토링
- 관리자 페이지 css 리팩토링
---
✅체크리스트
---
=> refactor: 메인, 회원 목록, 회원가입, 마이페이지, 관리자페이지 프론트 리팩토링

.gitignore, backend/Dockerfile, docker-compose.yml, frontend/Dockerfile, websocket-server/Dockerfile
🌟개요
---
도커파일, 도커컴포즈 세팅
🌐연결된 Issues
---
Closes #134 
📋작업사항
---
도커파일, 도커컴포즈 세팅
---
✅체크리스트
---
=> feat: 도커파일, 도커컴포즈 세팅

frontend/src/components/common/Header.vue
🌟개요
---
관리자 버튼 추가
🌐연결된 Issues
---
Closes #139 
📋작업사항
---
- 관리자 버튼 추가
---
✅체크리스트
---
=> feat: 관리자 버튼 추가

backend/src/main/java/com/shallwecode/backend/problem/domain/service/ProblemDomainService.java
🌟개요
---
문제 목록 조회 필터링 오류 수정
🌐연결된 Issues
---
Closes #142 
📋작업사항
---
- 문제 목록 조회 필터링 오류 수정
---
✅체크리스트
---
=> fix: 문제 목록 조회 필터링 오류 수정

backend/src/main/java/com/shallwecode/backend/problem/application/dto/FindMyCodingRoomResDTO.java, backend/src/main/java/com/shallwecode/backend/problem/domain/service/CodingRoomDomainService.java, frontend/src/components/user/MyCodingRoomList.vue
🌟개요
---
🌐연결된 Issues
---
Closes #144
📋작업사항
---
1) 마이페이지 참여 중 코딩방 목록에 있는 문제를 클릭하면 해당 코딩방으로 이동하는 기능 구현함.
---
✅체크리스트
---
=> feat: 마이페이지 참여 중 코딩방 이동시 해당 코딩방으로 이동 기능 구현

backend/src/main/java/com/shallwecode/backend/problem/application/dto/coop/CoopDTO.java, frontend/src/components/codingroom/ChatArea.vue
🌟개요
---
🌐연결된 Issues
---
Closes #152 
📋작업사항
---
---
✅체크리스트
---
=> feat: 협업 초대, 협업 탈퇴 버튼 생성

backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java, frontend/src/components/admin/ProbUpdateComponent.vue
🌟개요
📋작업사항
--- 프론트에서 accessToken만 전달하도록 코드 수정했습니다.
=> fix: 유저 수정 해결

frontend/src/views/Home.vue
🌟개요
---
🌐연결된 Issues
---
Closes #157 
📋작업사항
---
---
✅체크리스트
---
=> feat: 코딩방 생성시 confirm 창 설정 #157

README.md
🌟개요
---
🌐연결된 Issues
---
Closes #{이슈넘버}
📋작업사항
---
- Readme 기본 틀 작성
---
✅체크리스트
---
=> docs: ReadMe 생성 및 기본 틀 작성

backend/src/main/java/com/shallwecode/backend/problem/application/controller/CoopController.java, backend/src/main/java/com/shallwecode/backend/problem/application/service/CoopService.java, frontend/src/components/admin/ProbSaveComponent.vue, frontend/src/components/codingroom/ChatArea.vue
🌟개요
---
🌐연결된 Issues
#150 
📋작업사항
--- 원래 이슈 #155에 올렸어야 했는데 실수로 #150으로 올렸습니다.
--- 코딩방에서 친구 초대 및 나가기 기능 됩니다.
--- 호스트가 코딩방에서 나갈경우 해당 코딩방이 삭제되고, 협업 친구 목록도 삭제됩니다.
--- 친구 초대시 채팅방 목록에 반영 잘 됩니다.
--- 친구 초대 목록에서 중복해서 친구 초대 버튼을 누를 수 있는데 오늘중으로 수정 예정입니다.
=> feat: 코딩방 친구초대 및 나가기 구현

backend/src/test/java/com/shallwecode/backend/problem/domain/service/CodingRoomDomainServiceTest.java, backend/src/test/java/com/shallwecode/backend/problem/domain/service/CoopDomainServiceTest.java, backend/src/test/java/com/shallwecode/backend/problem/domain/service/ProblemDomainServiceTest.java
🌟개요
---
import 문제 해결
🌐연결된 Issues
---
Closes #164 
📋작업사항
---
- import 문제 해결
---
✅체크리스트
---
=> fix: import 오류 해결

backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java, backend/src/test/java/com/shallwecode/backend/user/application/service/UserServiceTest.java
🌟개요
---
🌐연결된 Issues
---
Closes #167 
📋작업사항
---
- 회원 조회(닉네임, id, 목록) 테스트 코드 구현
- 회원 닉네임 수정 테스트 코드 구현
- 회원 삭제 테스트 코드 구현
---
- 회원 삭제 시 코딩방 존재 확인 로직 추가
- 회원 조회 메소드 트랜잭셔널 추가
✅체크리스트
---
=> test: 회원 테스트코드 구현

backend/src/main/java/com/shallwecode/backend/oauth2/jwt/filter/JwtAuthenticationProcessingFilter.java, backend/src/main/java/com/shallwecode/backend/oauth2/service/CustomOAuth2UserService.java, backend/src/main/java/com/shallwecode/backend/problem/application/service/CoopService.java, backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java, backend/src/test/java/com/shallwecode/backend/user/application/service/NotiServiceTest.java, k8s_manifests/ingress-swc.yml
🌟개요
---
알림 테스트 코드 구현
🌐연결된 Issues
---
Closes #167 
📋작업사항
---
- 알림 테스트 코드 구현
---
✅체크리스트
---
=> test: 알림 테스트 코드 구현

frontend/src/components/common/Header.vue
🌟개요
---
프론트 간단한 수정
🌐연결된 Issues
---
Closes #{이슈넘버}
📋작업사항
---
---
✅체크리스트
---
=> chore: 간단한 수정
